
///*************** Icons ***********///
const iconAccount ='assets/images/icon_account.png';
const iconAbout ='assets/images/icon_about.png';
const iconBack ='assets/images/icon_back.png';
const iconBg ='assets/images/icon_bg.png';
const iconCall ='assets/images/icon_call.png';
const iconCarDelivery ='assets/images/icon_car_delivery.png';
const iconCart ='assets/images/icon_cart.png';
const iconCategories ='assets/images/icon_categories.png';
const iconCheck ='assets/images/icon_check.png';
const iconCities ='assets/images/icon_cities.png';
const iconClose ='assets/images/icon_close.png';
const iconCoins ='assets/images/icon_coins.png';
const iconDelete ='assets/images/icon_delete.png';
const iconDelivery ='assets/images/icon_delivery.png';
const iconDeliveryMethod ='assets/images/icon_delivery_method.png';
const iconEdit ='assets/images/icon_edit.png';
const iconFacebook ='assets/images/icon_facebook.png';
const iconFilter ='assets/images/icon_filter.png';
const iconHome ='assets/images/icon_home.png';
const iconInstagram ='assets/images/icon_instagram.png';
const iconLanguage ='assets/images/icon_language.png';
const iconLinkedin ='assets/images/icon_linkedin.png';
const iconLocation ='assets/images/icon_location.png';
///
const iconLogo ='assets/images/icon.png';
const iconLogoText ='assets/images/icon.png';
///
const iconLogout ='assets/images/icon_logout.png';
const iconMail ='assets/images/icon_mail.png';
const iconMaroof ='assets/images/icon_maroof.png';
const iconNotification ='assets/images/icon_notification.png';
const iconNotify ='assets/images/icon_notify.png';
const iconOrders ='assets/images/icon_orders.png';
const iconPaper ='assets/images/icon_paper.png';
const iconPolices ='assets/images/icon_polices.png';
const iconRefund ='assets/images/icon_refund.png';
const iconSearch ='assets/images/icon_search.png';
const iconShare ='assets/images/icon_share.png';
const iconSnapchat ='assets/images/icon_snapchat.png';
const iconTwitter ='assets/images/icon_twitter.png';
const iconWhatsapp ='assets/images/icon_whatsapp.png';
const iconWishlist ='assets/images/icon_wishlist.png';
const iconAddToCart ='assets/images/icon_add_to_cart.png';
const iconRemove ='assets/images/icon_remove.png';
const iconRemoveRed ='assets/images/icon_remove_red.png';
const iconMenu ='assets/images/icon_menu.png';
const iconTabby2 ='assets/images/tabby2.png';
const iconTamara2 ='assets/images/tamara2.png';

///*************** Images ***********///
const imageAppsBunches ='assets/images/image_apps_bunches.png';
const imageArt ='assets/images/image_art.png';
const imageProfile ='assets/images/image_edit_profile.png';
const imageSplash ='assets/images/image_splash.png';
const imageTax ='assets/images/image_tax.png';
